### PR TITLE
Astar algorithm and test cases added. Solved issue #13

### PR DESCRIPTION
**Pull request by virenvarma007**
I added the Astar algorithm with number of nodes in between goal and intermediate node as a heuristic value. Solved issue #13 and used it's linked pseudocode as reference.

### CODE REVIEW

**Comment by virenvarma007** [comment]
@jordanmontt I added a comment to Astar Algorithm. The PR is ready to merge now.

**Comment by jordanmontt** [comment]
I left some comments

**Comment by virenvarma007** [comment]
I made changes to the `run` method by removing the path return. I converted the heuristic function to Dijkstra.

**Comment by jordanmontt** [comment]
The use of the already implemented Dijkstra algo is still missing :)

**Comment by jordanmontt** [comment]
Thanks :)

**Pull request merged**
